### ISSUE TITLE
lcross machine training时候server所在卡上的OOM

### ISSUE THREAD

**Issue by iezhuozhuo** [SMILELab-FL/FedLab#182]
在cross machine mode training时候，server所在的卡上的gpu的占有量是 每一个client gpu占有量乘上client num数量，这样在大模型联邦训练时候导致OOM，是否是以下模型聚合code的问题：
`serialized_parameters = Aggregators.fedavg_aggregate(model_parameters_list) `
`SerializationTool.deserialize_model(self._model, serialized_parameters)`

**Comment by Zengdun-cs** [comment]
这个是pytorch分布式通信的机制问题，当server进程和client进程处于同一台物理机上时，server进程会自动生成一个对应的gpu bucket用于梯度同步，所以会导致多余内存占用。
目前版本暂未解决该问题，我们建议两个解决方案：
1. 用standalone或者scale场景的代码，用少量的进程资源模拟FL
2. 将server进程执行在一个独立的docker或者物理机上，与client进程分离。此时，不会触发gpu bucket机制，也就不会占用更多的显存。
