### ISSUE TITLE
框架支持分布式CPU训练吗

### ISSUE THREAD

**Issue by iswujie** [SMILELab-FL/FedLab#183]
请问该框架能够使用CPU训练吗，是否支持分布式CPU训练呢？

**Comment by Zengdun-cs** [comment]
支持cpu训练，client的trainer把cuda设置为false，就采用cpu计算。
分布式部署的话就和文档里写的一样。

**Comment by iswujie** [comment]
![%YB{{ P%NM72PYABK)11B8W](https://user-images.githubusercontent.com/78686094/145327751-a8d4277f-b795-47ac-87b3-ca0a052a68ab.png)
按照您所说将trainer的cuda设为false，但是会有如上报错：
我安装的是pytorch1.10的cpu版本，因为实验电脑没有gpu，其他环境设置按照您文档所给安装。

**Comment by Zengdun-cs** [comment]
这里是pynvml的报错，我们用这个库来获取最优可用gpu id。
可以把这个路径下的main.py的68， 70行注释掉，71行改为model = MLP().cpu()解决。
