### ISSUE TITLE
在FedLab中加入Yolov5，模型反序列化时报错

### ISSUE THREAD

**Issue by StarvenLan** [SMILELab-FL/FedLab#184]
(bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): LeakyReLU(negative_slope=0.1, inplace=True)
      (m): Sequential(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU()
          )
          (cv2): Conv(
            (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU()
          )
        )
      )
    )
    (21): Conv(
      (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU()
    )
    (22): Concat()
    (23): BottleneckCSP(
      (cv1): Conv(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU()
      )
      (cv2): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (cv3): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (cv4): Conv(
        (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
        (act): SiLU()
      )
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): LeakyReLU(negative_slope=0.1, inplace=True)
      (m): Sequential(
        (0): Bottleneck(
          (cv1): Conv(
            (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU()
          )
          (cv2): Conv(
            (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU()
          )
        )
      )
    )
    (24): Detect(
      (m): ModuleList(
        (0): Conv2d(128, 255, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(256, 255, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(512, 255, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
)
recive_serialize:   tensor([ 0.01084, -0.01686, -0.01511,  ...,  0.04360, -3.90503,  4.08698])
Traceback (most recent call last):
  File "/home/canghai/yolov5_6/client_train.py", line 691, in <module>
    main(opt)
  File "/home/canghai/yolov5_6/client_train.py", line 588, in main
    train(opt.hyp, opt, device, callbacks, network, wandb)
  File "/home/canghai/yolov5_6/client_train.py", line 288, in train
    SerializationTool.deserialize_model(
  File "/home/canghai/yolov5_6/fedlab/utils/serialization.py", line 65, in deserialize_model
    parameter.data.copy_(serialized_parameters[current_index:current_index + numel].view(size))
RuntimeError: shape '[255, 128, 1, 1]' is invalid for input of size 16182

1、最开始为yolov5model
2、客户端收到的序列化的结果
3、报错信息

**Comment by Zengdun-cs** [comment]
这里提供一个序列化/反序列化模块的单元测试代码：
```
model = 你的yolov5模型
serialized_params = SerializationTool.serialize_model(model)
m_params = torch.Tensor([0])
for param in model.parameters():
    m_params = torch.cat((m_params, param.data.view(-1)))
m_params = m_params[1:]
assert torch.equal(serialized_params, m_params)

def model_params_eq(model1, model2):
        for param1, param2 in zip(model1.parameters(), model2.parameters()):
            assert torch.equal(param1, param2)

model_test = 随机初始化的相同模型
SerializationTool.deserialize_model(model_test, m_params)
model_params_eq(model_test, model)
```

1. 通过上面的代码检测是否是我们的序列化模块对yolov5的模型出错。
2. 如果上面的代码没有报错，请检查您的代码中调用SerializationTool.deserialize_model(model, parameters)时，parameters.shape 是否与SerializationTool.serialize_model(model)返回的向量的shape一致。

**Comment by Zengdun-cs** [comment]
关于FedLab点对点通信模块，目前仍有一些限制，会在未来的版本里完善，请查看文档。
https://fedlab.readthedocs.io/zh_CN/docs-fix-en-version/tutorials/tutorial_1.html

**Comment by AgentDS** [comment]
你能直接把这个需要序列化的模型数据存成文件以及你怎么序列化这个模型的代码提供给我们吗，可能是我们这边设计的时候默认了数据的shape格式，所以序列化的时候出错了
