### ISSUE TITLE
可以咨询一下关于联邦学习框架选择吗

### ISSUE THREAD

**Issue by carrier106** [SMILELab-FL/FedLab#191]
学长，我从河畔看到帖子到这里的，最近打算做联邦学习，fedlab不在现有综述的推荐里，当时框架选择您是如何选择的？
![image](https://user-images.githubusercontent.com/48007158/156961694-2c1b0192-962a-4d8e-ad49-0fc5ca00a7f9.png)

**Comment by AgentDS** [comment]
你好，谢谢对FedLab的兴趣，有些FL survey写得可能比较早，这些框架我们调研的时候也查到过的。大部分这些是工业落地或者有特定场景的，比如金融医疗或者更强调安全计算加密相关。我们框架主打实验室快速demo实现，更多是算法的模拟运行，就是方便实验室环境下idea的快速验证。

**Comment by carrier106** [comment]
谢谢学长的回答。
