### ISSUE TITLE
支持嵌入式设备和服务器（或者电脑）进行联邦学习吗

### ISSUE THREAD

**Issue by carrier106** [SMILELab-FL/FedLab#198]
跨机场景允许用户在多机集群内模拟联邦学习系统。在本页面中的场景下，我们改用localhost作为server地址。一共启动了三个进程来执行联邦学习流程。    这个同一网络内包括嵌入式设备也可以吗？

**Comment by Zengdun-cs** [comment]
理论上只要进程所在环境能够安装pytorch环境就可以。

但是多机情况下，要进程互联的话localhost作为server进程ip应该是不行的，server进程需要的是一个局域网ip地址。

**Comment by carrier106** [comment]
那意思是这个框架按理是支持的。那我看看代码试一下。

**Comment by Zengdun-cs** [comment]
好的，有问题欢迎反馈。
