### ISSUE TITLE
AttributeError: 'FedAvgTrainer' object has no attribute 'gpu'

### ISSUE THREAD

**Issue by HongdaChen** [SMILELab-FL/FedLab#229]
**Describe the bug**
if I use cpu to train a model, then the error will be traggered:

`AttributeError: 'FedAvgTrainer' object has no attribute 'gpu'`

I have fixed it by :

add this code to line 38 in `fedlab/core/model_maintainer.py`:

`self.gpu = None`

**Comment by Zengdun-cs** [comment]
if you want to initialize a trainer on CPU, just set the attribute "cuda=False" at the init function.
