### ISSUE TITLE
fedlab.utils.dataset.partition.CIFAR10Partitioner tool running take extrem long time

### ISSUE THREAD

**Issue by LeonMac** [SMILELab-FL/FedLab#230]
**Describe the bug**
Using fedlab.utils.dataset.partition.CIFAR10Partitioner tool for cifar10 dataset partitioning.
Other options looks OK, but when trying the "unbalance_dirichlet", i.e. adopting the below setup:
```
    dirichlet_alpha :float = 0.3   # only for Dirichlet distribution, balance or unbalance
    unbalance_sgm: float   = 0.3   # for all unbalance partition
        trainset_part_u = CIFAR10Partitioner( trainset.targets,
                                                num,
                                                balance=False,
                                                partition="dirichlet",
                                                unbalance_sgm=unbalance_sgm,
                                                dir_alpha=dirichlet_alpha,
                                                seed=seed)

        trainset_part_b = CIFAR10Partitioner( trainset.targets,
                                                num_clients,
                                                balance=True,
                                                partition="dirichlet",
                                                dir_alpha=dirichlet_alpha,
                                                seed=seed)

```
the log report show the partitioning task is running and taking a very long time--most likely >5 min. not a reasonable time.
```
Remaining Data: 4784
Remaining Data: 4783
Remaining Data: 4782
Remaining Data: 4782
Remaining Data: 4781
....
```
as a comparison, if using the below setup, it works fine, partitioning can be completed in seconds' time
```
        trainset_part_n = CIFAR10Partitioner(trainset.targets,
                                            num_clients,
                                            balance=None,
                                            partition="dirichlet",
                                            dir_alpha=dirichlet_alpha,
                                            seed=seed)

```

**Environment**
Environment you use when bug appears:
1. Python version : 3.7.10
2. PyTorch Version: 1.11.0, pytorchvision 0.12.0
3. FedLab version: 1.2.1
4. code you run (see above)
5. the detailed error (see above)

**Additional context**

**Comment by AgentDS** [comment]
The function for "balance=True" is from [FedDyn](https://github.com/alpemreacar/FedDyn) repo. We use their partition code when replicating their results.

**Comment by LeonMac** [comment]
I have such problem for balance=True, and balance=False, but no problem for balance=None.
I was using the same rand number 2021 as the example code.
Just tried a few other seed numbers, I find 2022 is acceptable (~10 seconds can be finished) but something like 2021/2023/100 are all slow.

**Comment by LeonMac** [comment]
OK, then this usage is limited if the user needs to have a different seed (for generating different partition)..
