### ISSUE TITLE
苹果M1芯片运行出错

### ISSUE THREAD

**Issue by eccstartup** [SMILELab-FL/FedLab#233]
**Describe the bug**
cross-process-mnist/launch_eg.sh 执行出现错误

**Environment**
Environment you use when bug appears:
1. Python version: 3.9.12
2. PyTorch Version: 1.12.0
3. FedLab version: 1.2.1
4. code you run: examples/cross-process-mnist/launch_eg.sh
5. the detailed error:
libc++abi: terminating with uncaught exception of type gloo::EnforceNotMet: [enforce fail at /Users/runner/work/pytorch/pytorch/pytorch/third_party/gloo/gloo/transport/uv/pair.cc:248] op.nread == op.preamble.nbytes. 

**Additional context**

$ /bin/bash /Users/eccstartup/code/github/FedLab/examples/cross-process-mnist/launch_eg.sh
20:59:28 - network 0 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3001, rank 0, world size: 3, backend gloo, ethernet None.
20:59:28 - network 1 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3001, rank 1, world size: 3, backend gloo, ethernet None.
20:59:28 - network 2 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3001, rank 2, world size: 3, backend gloo, ethernet None.
20:59:28 - torch.distributed.distributed_c10d - INFO - Added key: store_based_barrier_key:1 to store for rank: 0
20:59:28 - torch.distributed.distributed_c10d - INFO - Added key: store_based_barrier_key:1 to store for rank: 2
20:59:28 - torch.distributed.distributed_c10d - INFO - Added key: store_based_barrier_key:1 to store for rank: 1
20:59:28 - torch.distributed.distributed_c10d - INFO - Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
20:59:28 - torch.distributed.distributed_c10d - INFO - Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
20:59:28 - torch.distributed.distributed_c10d - INFO - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
20:59:28 - network 1 - INFO - Sent package to destination 0, message code MessageCode.SetUp, content length 1
libc++abi: terminating with uncaught exception of type gloo::EnforceNotMet: [enforce fail at /Users/runner/work/pytorch/pytorch/pytorch/third_party/gloo/gloo/transport/uv/pair.cc:248] op.nread == op.preamble.nbytes. 
/Users/eccstartup/code/github/FedLab/examples/cross-process-mnist/launch_eg.sh: line 9:  1365 Abort trap: 6           python server.py --ip 127.0.0.1 --port 3001 --world_size 3 --round 3
libc++abi: libc++abi: terminating with uncaught exception of type std::__1::system_error: Connection reset by peerterminating with uncaught exception of type std::__1::system_error: Connection reset by peer

/Users/eccstartup/code/github/FedLab/examples/cross-process-mnist/launch_eg.sh: line 9:  1366 Abort trap: 6           python client.py --ip 127.0.0.1 --port 3001 --world_size 3 --rank 1
/Users/eccstartup/code/github/FedLab/examples/cross-process-mnist/launch_eg.sh: line 9:  1367 Abort trap: 6           python client.py --ip 127.0.0.1 --port 3001 --world_size 3 --rank 2

**Comment by eccstartup** [comment]
[runtime.txt](https://github.com/SMILELab-FL/FedLab/files/9190147/runtime.txt)

**Comment by Zengdun-cs** [comment]
经过在macos测试发现了同样的问题，但是没有找到合适的解决方案。
我猜测是torch.distributed的通信接口和macos存在某种冲突导致的这个问题。

**Comment by eccstartup** [comment]
嗯嗯，我换了好几个版本的pytorch，都有同样的错误。csdn有个链接还打不开

https://blog.csdn.net/qq_37514135/article/details/117196294

**Comment by AgentDS** [comment]
还是建议Linux上使用吧。比较全面的测试是在Linux上做的

**Comment by eccstartup** [comment]
> 还是建议Linux上使用吧。比较全面的测试是在Linux上做的

嗯嗯，fed软件一大堆，已经弃坑了。
