### ISSUE TITLE
Cant run the quickstart demo of standalone.py

### ISSUE THREAD

**Issue by Refrain-123** [SMILELab-FL/FedLab#266]
**Describe the bug**
Traceback (most recent call last):
  File "examples/standalone-mnist/standalone.py", line 18, in <module>
    from fedlab.models.mlp import MLP
ModuleNotFoundError: No module named 'fedlab.models'

I follow the guide in https://fedlab.readthedocs.io/zh_CN/latest/examples/quick_start.html to run a demo, but get the above question, dose anyone else who has the same problem?

**Comment by Zengdun-cs** [comment]
We are updating FedLab recently. Please follow the quick start section in README.md.
The python script is [here](https://github.com/SMILELab-FL/FedLab/tree/master/examples/standalone-mnist).
Please let me know if you encounter other problems.

**Comment by Zengdun-cs** [comment]
We encourage you to install FedLab via source code.
We will release the latest version to PyPI later.

**Comment by Refrain-123** [comment]
> We encourage you to install FedLab via source code. We will release the latest version to PyPI later.

I see, but I just git clone the repo via source code as you recommend and install the packages in requirements.txt . Did I miss some operation to run the demo standalone.py?

**Comment by AgentDS** [comment]
Hi, MLP is just an example model to run the demo, you can just copy the MLP code into you script: 
```
class MLP(nn.Module):
    def __init__(self, input_size, output_size):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, 200)
        self.fc2 = nn.Linear(200, 200)
        self.fc3 = nn.Linear(200, output_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = x.view(x.shape[0], -1)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x
```

**Comment by Refrain-123** [comment]
> Hi, MLP is just an example model to run the demo, you can just copy the MLP code into you script:
> 
> ```
> class MLP(nn.Module):
>     def __init__(self, input_size, output_size):
>         super(MLP, self).__init__()
>         self.fc1 = nn.Linear(input_size, 200)
>         self.fc2 = nn.Linear(200, 200)
>         self.fc3 = nn.Linear(200, output_size)
>         self.relu = nn.ReLU()
> 
>     def forward(self, x):
>         x = x.view(x.shape[0], -1)
>         x = self.relu(self.fc1(x))
>         x = self.relu(self.fc2(x))
>         x = self.fc3(x)
>         return x
> ```

Did you mean copy this part into the standalone.py?

**Comment by Refrain-123** [comment]
Traceback (most recent call last):
  File "standalone.py", line 20, in <module>
    from fedlab.contrib.algorithm.basic_server import SyncServerHandler
ModuleNotFoundError: No module named 'fedlab.contrib'

And it seems the problem also lies for other packages :(

**Comment by Zengdun-cs** [comment]
This seems some import path config problems.  You are supposed to do these 2 steps with the correct version of PyTorch in your env.

1. $ cd FedLab/examples/standalone/

2. $ bash python standalone.py --total_client 100 --com_round 3 --sample_ratio 0.1 --batch_size 100 --epochs 5 --lr 0.02

Then you may get the following output in the terminal.

![image](https://user-images.githubusercontent.com/32679207/194487594-254b0155-3828-47e7-a17c-ea71222e0a75.png)

Or you could try this [jupyter notebook](https://github.com/SMILELab-FL/FedLab/blob/master/tutorials/pipeline_tutorial.ipynb), which is the same as the standalone demo.

**Comment by Refrain-123** [comment]
> This seems some import path config problems. You are supposed to do these 2 steps with the correct version of PyTorch in your env.
> 
> 1. $ cd FedLab/examples/standalone/
> 2. $ python standalone.py --total_client 100 --com_round 3 --sample_ratio 0.1 --batch_size 100 --epochs 5 --lr 0.02
> 
> Then you may get the following output in the terminal.
> 
> ![image](https://user-images.githubusercontent.com/32679207/194487594-254b0155-3828-47e7-a17c-ea71222e0a75.png)
> 
> Or you could try this [jupyter notebook](https://github.com/SMILELab-FL/FedLab/blob/master/tutorials/pipeline_tutorial.ipynb), which is the same as the standalone demo.

Yes, just as what you mentioned in https://fedlab.readthedocs.io/en/master/examples/quick_start.html#quickstart , and I did nothing else. I was wondering whether I have to git clone a stable version of Fedlab, as I just go to the repo and do "git clone https://github.com/SMILELab-FL/FedLab.git", is it because of the latest version that I've encountered this problem?

**Comment by Zengdun-cs** [comment]
Yes, you should clone the master branch version.

**Comment by Refrain-123** [comment]
> Yes, you should clone the master branch version.

That's what I did, as the master branch version is the default one. It's ok if this doesn't work for me. Can I run some demo by clone the benchmark-repo?

**Comment by Zengdun-cs** [comment]
> > Yes, you should clone the master branch version.
> 
> That's what I did, as the master branch version is the default one. It's ok if this doesn't work for me. Can I run some demo by clone the benchmark-repo?

The benchmark-repo relys on previous version of FedLab (v1.2.1). You can run benchmark-repo demo by installing the old
 version.

But, we still encourage you to use the latest version (v1.3.0-alpha), because it is quite different from v.1.2.1. We have moved most demos in benchmark-repo to this repo now (testing). 

Have you tried [jupyter notebook](https://github.com/SMILELab-FL/FedLab/blob/master/tutorials/pipeline_tutorial.ipynb)? I think there are some tiny configuration errors in your python environments because we have tested the quick start. It works fine in our test environment. Maybe running the jupyter notebook could help you to solve that.
