### ISSUE TITLE
Implementation bug of fedprox

### ISSUE THREAD

**Issue by KPollux** [SMILELab-FL/FedLab#280]
**Describe the bug**
In [fedlab/contrib/algorithm/fedprox.py](https://github.com/SMILELab-FL/FedLab/blob/6edcfb3ee81efb1ab4aee973f731451c53a490eb/fedlab/contrib/algorithm/fedprox.py) 
Line 59, 60. The loss calculation code seems to mistakenly override the correct implementation of fedprox.

**Comment by Zengdun-cs** [comment]
Yes, it is a mistake. We will fix it later. Thank you so much.
