### ISSUE TITLE
如何通过划分得到与划分前相同数据结构的数据？

### ISSUE THREAD

**Issue by Sugariscool** [SMILELab-FL/FedLab#284]
我通过以下代码 获得cifar10数据集
`trainset = datasets.CIFAR10(root='data/CIFAR10', train=True, download=True)`
其数据类型为`torchvision.datasets.cifar.CIFAR10`
我想通过划分数据，使得每个客户端得到的数据类型都为`torchvision.datasets.cifar.CIFAR10`这该怎么做？

**Comment by Zengdun-cs** [comment]
关于划分Cifar10数据集的方案，请参考我们给出的[示例](https://github.com/SMILELab-FL/FedLab/blob/master/fedlab/contrib/dataset/partitioned_cifar10.py)。

**Comment by Sugariscool** [comment]
> 关于划分Cifar10数据集的方案，请参考我们给出的[示例](https://github.com/SMILELab-FL/FedLab/blob/master/fedlab/contrib/dataset/partitioned_cifar10.py)。

成功了！谢谢~
