### ISSUE TITLE
Explanation of the partition function for client_inner_dirichlet_partition function 

### ISSUE THREAD

**Issue by kaurish** [SMILELab-FL/FedLab#291]
**Describe the bug**
In the function client_inner_dirichlet_partition(), the prior_cumsum does not seem to be updated after every loop. In that way how does it still follow Dirichlet distribution? 
For example in the first loop client 4 is selected and from the class 8 is selected. In next iteration based of random function call, diff client and class will be selected. The number of remaining class elements are getting updated and the number of elements needed by per class is getting updated but the Dirichlet distribution value is not. Can you please provide more detail on how the following line 287 in functon.py helps in Dirichlet distribution ?

**Comment by kaurish** [comment]
<img width="1297" alt="Screen Shot 2023-02-11 at 2 50 57 PM" src="https://user-images.githubusercontent.com/123860308/218284420-1997f03a-608d-4f4e-a07d-9e9f0b654714.png">

**Comment by AgentDS** [comment]
suggest to use the code below if you want to debug like this:
r = np.random.uniform()  # line 286
curr_class = np.argmax(r <= curr_prior)  # line 287

**Comment by AgentDS** [comment]
line 287 is just something sampling method to get the curr_class

**Comment by AgentDS** [comment]
prior_cumsum is fixed for the later sampling method. Sampling samples to assign to the client sampled on the current loop until the prior_cumsum is met. Actually, we can use other random method without sampling.
