### ISSUE TITLE
Where is the 'model' directory in this path (datasets/reddit) ?

### ISSUE THREAD

**Issue by xiyiyia** [SMILELab-FL/FedLab#294]
**Describe the bug**

There is no directory whose name is model, and I can't find the model of stacked_lstm.
How do I use this dataset (reddit)?

**Comment by Zengdun-cs** [comment]
We are sorry for the misleading. Reddit dataset is not supported by FedLab currently. 
The README about reddit is from the original repo [LEAF](https://github.com/TalwalkarLab/leaf/tree/master/models). For now, FedLab supports FEMNIST, ShakeSpeare, Sent140, and CelebA datasets with pytorch [datasets](https://github.com/SMILELab-FL/FedLab/blob/master/datasets/leaf_datasets.py).

**Comment by xiyiyia** [comment]
> We are sorry for the misleading. Reddit dataset is not supported by FedLab currently. The README about reddit is from the original repo [LEAF](https://github.com/TalwalkarLab/leaf/tree/master/models). For now, FedLab supports FEMNIST, ShakeSpeare, Sent140, and CelebA datasets with pytorch [datasets](https://github.com/SMILELab-FL/FedLab/blob/master/datasets/leaf_datasets.py).

@Zengdun-cs Thanks for your prompt reply.
