### ISSUE TITLE
分布式通信部署时，卡在network.init_network_connection()函数

### ISSUE THREAD

**Issue by LinkWithMe** [SMILELab-FL/FedLab#296]
**Describe the bug**
分布式通信部署时，卡在network.init_network_connection()函数

**Environment**
执行代码：
```
from fedlab.core.network import DistNetwork
world_size = 10
rank = 0  
ethernet = "eth0"
server_ip = '198.168.206.15'
server_port = 2244
address=(server_ip, server_port)
network = DistNetwork(address, world_size, rank, ethernet)
network.init_network_connection()
print(111)
network.close_network_connection() 
```
在network实例化之后，不再往下进行：
![图片](https://user-images.githubusercontent.com/57388780/233651797-5066ef8a-310b-4ef8-a9d6-a6d1640e2fed.png)
ifconfig命令信息如下：
![图片](https://user-images.githubusercontent.com/57388780/233651934-758b1124-3800-4ebc-9c58-fed84742442d.png)

**Comment by LinkWithMe** [comment]
最后显示报错：
![图片](https://user-images.githubusercontent.com/57388780/233773622-12c3c513-8306-4638-9ef4-e6a28b829222.png)

**Comment by Zengdun-cs** [comment]
网络初始化需要对应的client端建立连接了才能初始化成功。
这里提供了一个[网络初始化测试脚本](https://github.com/SMILELab-FL/FedLab/tree/master/examples/network-connection-checker)

**Comment by AgentDS** [comment]
world_size = 10总共要开10个这样的脚本（包括一个server和9个client）

**Comment by LinkWithMe** [comment]
![图片](https://user-images.githubusercontent.com/57388780/233894433-f46ba04a-5712-4642-aec8-8cc616ab3a56.png)
解决了！谢谢谢谢谢谢谢谢

**Comment by LinkWithMe** [comment]
已经解决！感谢大佬感谢大佬



想养只猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SMILELab-FL/FedLab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SMILELab-FL/FedLab] 分布式通信部署时，卡在network.init_network_connection()函数 (Issue #296)





 
网络初始化需要对应的client端建立连接了才能初始化成功。
 这里提供了一个网络初始化测试脚本

**Comment by LinkWithMe** [comment]
已经解决！感谢大佬感谢大佬！还是自己torch.distributed使用的不够熟练


想养只猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SMILELab-FL/FedLab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SMILELab-FL/FedLab] 分布式通信部署时，卡在network.init_network_connection()函数 (Issue #296)





 
world_size = 10总共要开10个这样的脚本（包括一个server和9个client）
