### ISSUE TITLE
关于standalone单机进程部署方案进行代码测试遇到的问题 issues about using standalone deployment scenario to testing code

### ISSUE THREAD

**Issue by JLUssh** [SMILELab-FL/FedLab#298]
作者，您好，感谢您为我们提供这么样一个方便的框架。
目前在使用这个框架时，我遇到了一些问题：
在进行standalone单机部署场景时，使用数据集CIFAR10，模型为CNN-CIFAR10或AlexNet_CIFAR10，划分方案是paritation=‘dirichlet’，dir_alpha=0.3, balance=None。
在standalone.py中的类StandalonePipeline中定义了其evaluate方法，用cifar10的测试数据集对 self.handler._model进行测试，有时候会发现这个服务器模型的精度，在前几十轮，基本是逐步上升的，但在一定阶段后，它的精度对骤降到一个很小的值，并基本保持这个值不变，请问这是什么原因呢？这样的情况也是偶尔出现，有时候能正常运行完定义的communication_round.
因为我想将贵方的框架用做我将要做的工作的基础框架，加以引用，所以希望能话，麻烦作者能帮我解惑，感谢。

Thank you for your excellent work!
when I using the framework, I have meet some questions:
I try to use the standalone deployment scenario to simply testing code,  the experiment setting is: CIFAR10 dataset, CNN_CIFAR10 model, partition method is 'dirichlet', dir_alpha is equal to 0.3, balance is None.
I have self-define the evaluate method in the class StandalonePipeline in standalone.py file, when i using the test dataset to test self.handler._mode(I think it is the server side model), the accuracy is gradually increasing in  the first dozen rounds with the client-server communication, while it occasionally plummeting to a very smell accuracy rate and fluctuatint without any improvement. I had run with AlexNet_CIFAR10 using  com_round = 200 normally and got normal result, but I also meet this problem in AlexNet_CIFAR10 model too.

![image](https://user-images.githubusercontent.com/99879907/233818753-20718c7f-a11d-4a95-a3e8-e57cb67d1e4c.png)

**Comment by Zengdun-cs** [comment]
这是优化器超参数没设置好带来的问题，可以适当调小学习率试下。

**Comment by AgentDS** [comment]
大概是多少个client呢？感觉就是没有收敛

**Comment by JLUssh** [comment]
> 这是优化器超参数没设置好带来的问题，可以适当调小学习率试下。

感谢回复，好的，我试试，但我用的是样例的配置，且在前几十轮是能够正常测试模型精度的。。

**Comment by JLUssh** [comment]
> 这是优化器超参数没设置好带来的问题，可以适当调小学习率试下。

learning rate调小后，确实能正常运行定义的com_round了，抱歉拿这么简单的问题询问两位学长了，感谢，问题已解决。

**Comment by JLUssh** [comment]
> 大概是多少个client呢？感觉就是没有收敛

learning rate调小后，能正常运行定义的com_round了。抱歉拿这么简单的问题询问两位学长了，感谢，问题已解决。
