### ISSUE TITLE
Error in Example asynchronous-cross-process-mnist

### ISSUE THREAD

**Issue by pratik98** [SMILELab-FL/FedLab#299]
**Describe the bug**
I am trying to run the asynchronous-cross-process-mnist example on my machine. but getting an error.  

**Environment**
Environment you use when bug appears:
1. Python version : 3.8.3
2. PyTorch Version : 2.0.1
3. FedLab version 
4. code you run
5. the detailed error

**Server**
`python.exe .\server.py --world_size 3`

`16:46:18 - network 0 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 0, world size: 3, backend gloo, ethernet None.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:3002 (system error: 10049 - The requested address is not valid in its context.).`

**Client**

`python client.py --world_size 3 --rank 1 --epoch 10`
`16:47:30 - network 1 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 1, world size: 3, backend gloo, ethernet None.
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:3002 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:3002 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "client.py", line 59, in <module>
    Manager.run()
  File "../..\fedlab\core\network_manager.py", line 37, in run
    self.setup()
  File "../..\fedlab\core\client\manager.py", line 43, in setup
    super().setup()
  File "../..\fedlab\core\network_manager.py", line 48, in setup
    self._network.init_network_connection()
  File "../..\fedlab\core\network.py", line 67, in init_network_connection
    dist.init_process_group(
  File "C:\Projects\FedLab\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Projects\FedLab\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1009, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: Socket Timeout`

**Comment by Zengdun-cs** [comment]
According to the info, the errors come from the failure of network initialization. It would help if you tried running [network connection test](https://github.com/SMILELab-FL/FedLab/tree/master/examples/network-connection-checker) first.

**Comment by Zengdun-cs** [comment]
"I am unable to figure out the ethernet name on my windows machine. ipconfig says Ethernet adapter Ethernet 4 but it doesn't work" 

Please show me the outputs by ifconfig command
