### ISSUE TITLE
The example of SGDClientTrainer

### ISSUE THREAD

**Issue by ElegantLin** [SMILELab-FL/FedLab#301]
Hello, I found that [SGDSerialClientTrainer](https://fedlab.readthedocs.io/en/master/autoapi/fedlab/contrib/algorithm/index.html#fedlab.contrib.algorithm.SGDSerialClientTrainer) is dropped so I simply replace all [SGDSerialClientTrainer](https://fedlab.readthedocs.io/en/master/autoapi/fedlab/contrib/algorithm/index.html#fedlab.contrib.algorithm.SGDSerialClientTrainer) as SGDClientTrainer. But it seems that it does not work. Could you please help me with the merge?

Thanks!

**Comment by Zengdun-cs** [comment]
SGDSerialClientTrainer is not dropped. We are sorry for the misleading information, which we will remove as soon as possible. SGDSerialClientTrainer is used to simulate multiple clients in a single process. You can find the differences between SGDSerialClientTrainer and SGDClientTrainer [here](https://github.com/SMILELab-FL/FedLab/blob/master/tutorials/customize_tutorial.ipynb). And our [examples](https://github.com/SMILELab-FL/FedLab/tree/master/examples) of standalone and cross-process.

**Comment by ElegantLin** [comment]
Thanks for your timely response. Can I understand that SGDSerialClientTrainer is for single process while SGDClientTrainer is for multiple processes?

Thanks!

**Comment by Zengdun-cs** [comment]
Nor precisely. 
Actually, both of them can be used in a multiple processes simulation. SGDClientTrainer can be viewed as a special case of SGDSerialClientTrainer (num_clients=1). We describe our design in [Overview](https://fedlab.readthedocs.io/en/master/overview.html). You can see more information in [scale-mnist](https://github.com/SMILELab-FL/FedLab/tree/master/examples/scale-mnist) and [hybrid](https://github.com/SMILELab-FL/FedLab/tree/master/examples/hierarchical-hybrid-mnist).

**Comment by ElegantLin** [comment]
Got it. SGDClientTrainer is for launching the server and client processes separately, while SGDSerialClientTrainer is used for training the server and client in a single process. For example, in [scale-mnist](https://github.com/SMILELab-FL/FedLab/tree/master/examples/scale-mnist), there are two bash files to start the training while there is only one file to start in the standalone example.
