### ISSUE TITLE
A few modifications cause `standalone.py` to fail.

### ISSUE THREAD

**Issue by bird-two** [SMILELab-FL/FedLab#303]
Thanks for this clear and usefull open code for Federated Learning.

I make a few modifications to the file `standalone.py` (FedLab/examples/standalone-mnist/standalone.py).
![image](https://github.com/SMILELab-FL/FedLab/assets/70316218/59f9b475-cd1f-4bf2-a8b6-e9ec0a77e536)

I found that this modification cause the command `python standalone.py --total_client 100 --com_round 3 --sample_ratio 0.1 --batch_size 100 --epochs 5 --lr 0.02` to fail, which runs well when using the original code. Could you provide more details about how to use the other partitions? 

In addtion, more simple examples (that can be validated easily) would be better for the popularity of this code. 

![image](https://github.com/SMILELab-FL/FedLab/assets/70316218/76a0bab2-ac4f-48f8-8aa9-5ea87857bb77)

Thanks for your time to check this issue.

**Comment by Zengdun-cs** [comment]
This failure is caused by the false alignment of data preprocess and model input. 

The codes below show my usage of "PartitionedMNIST". You may add an additional transform `transform=transforms.Compose(
                                    [transforms.ToPILImage(), transforms.ToTensor()]))` to your code.
```
dataset = PartitionedMNIST(root="./datasets/mnist/",
                          path="./datasets/mnist/fedmnist_{}/".format(args.dir),
                          num_clients=args.num_clients,
                          partition="noniid-labeldir",
                          dir_alpha=args.dir,
                          seed=args.dseed,
                          preprocess=args.preprocess,
                          download=True,
                          verbose=True,
                          transform=transforms.Compose(
                              [transforms.ToPILImage(), transforms.ToTensor()]))
```

For the definition of other parameters, please see our tutorial.

**Comment by bird-two** [comment]
Thanks for your advice, yet I still failed with the same runtime error. I used four setttings below. (1) I deleted the generated `.pkl` file at the begining of each run; (2) I did not make any modification to the original code except what I showed below.

```
[Basic setting]
dataset = PartitionedMNIST(root="../../datasets/mnist/",
                          path="../../datasets/mnist/",
                          num_clients=args.total_client,
                          partition="iid",
                          dir_alpha=1.0,
                          seed=0,
                          preprocess=True,
                          download=True,
                          verbose=True,
                          transform=transforms.Compose(
                              [transforms.ToPILImage(), transforms.ToTensor()]))
```
```
[Four cases]
1. transform=transforms.Compose(
                              [transforms.ToPILImage(), transforms.ToTensor()])
2. transform=transforms.Compose(
                              [transforms.ToTensor()])
3. transform=transforms.Compose(
                              [transforms.ToTensor()]), 
    target_transform=transforms.Compose(
                              [transforms.ToTensor()])
4. transform=transforms.Compose(
                              [transforms.ToPILImage(), transforms.ToTensor()]), 
    target_transform=transforms.Compose(
                              [transforms.ToPILImage(), transforms.ToTensor()])
```

**Comment by AgentDS** [comment]
you dont need to use target_transform actually

**Comment by AgentDS** [comment]
The demo in branch release-1.3.0 works. Please check this version.

**Comment by AgentDS** [comment]
> Thanks for this clear and usefull open code for Federated Learning.
> 
> I make a few modifications to the file `standalone.py` (FedLab/examples/standalone-mnist/standalone.py). ![image](https://user-images.githubusercontent.com/70316218/241697296-59f9b475-cd1f-4bf2-a8b6-e9ec0a77e536.png)
> 
> I found that this modification cause the command `python standalone.py --total_client 100 --com_round 3 --sample_ratio 0.1 --batch_size 100 --epochs 5 --lr 0.02` to fail, which runs well when using the original code. Could you provide more details about how to use the other partitions?
> 
> In addtion, more simple examples (that can be validated easily) would be better for the popularity of this code.
> 
> ![image](https://user-images.githubusercontent.com/70316218/241697824-76a0bab2-ac4f-48f8-8aa9-5ea87857bb77.png)
> 
> Thanks for your time to check this issue.

For more usage of partition, please [check this](https://fedlab.readthedocs.io/en/master/tutorials/dataset_partition.html), the function parameters are almost the same, and you can also see the visualization result of these partition methods.

**Comment by AgentDS** [comment]
We are still adding more features to the dataset interface, which may lead to some inconsistency in the code. The tutorials shown above are for the previous version but can still be helpful if you want to use in release-1.3.0

**Comment by AgentDS** [comment]
Also please check [PartitionedMNIST](https://github.com/SMILELab-FL/FedLab/blob/release-v1.3.0/fedlab/contrib/dataset/partitioned_mnist.py); we directly use MNISTPartitioner here. You can replace this for other datasets. Also check [this](https://github.com/SMILELab-FL/FedLab/blob/release-v1.3.0/fedlab/contrib/dataset/partitioned_cifar10.py). All partitioners are provided [here](https://github.com/SMILELab-FL/FedLab/blob/release-v1.3.0/fedlab/utils/dataset/partition.py).
