### ISSUE TITLE
Not common usage of `AverageMeter`

### ISSUE THREAD

**Issue by bird-two** [SMILELab-FL/FedLab#304]
Thanks for your valuable time for checking this issue. This is a enhancement issue.

I found that the package use a not common function `AverageMeter()` in `FedLab/fedlab/utils /functional.py`, which may cause misuses. In fact, I found that `self.sum += val * n ` is more common, e.g., [1].
```
class AverageMeter(object):
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0.0
        self.avg = 0.0
        self.sum = 0.0
        self.count = 0.0

    def update(self, val, n=1):
        self.val = val
        self.sum += val 
        self.count += n
        self.avg = self.sum / self.count
```
Using this, we can solve the problem [2] with defining `evaluate()` (see `accuracy()` at [1]) as
```
acc1, acc5 = accuracy(output, target, topk=[1,5])
losses.update(loss.item(), target.size(0))
top1.update(acc1.item(), target.size(0))
top5.update(acc5.item(), target.size(0))
```

Ref:
[1] https://github.com/facebookresearch/moco/blob/main/main_lincls.py
[2] https://github.com/SMILELab-FL/FedLab/issues/186#issuecomment-1007228292

**Comment by AgentDS** [comment]
Yes, tahnk you for this issue. Actually, we have noticed this in our experiment :) The standard code should be
`self.sum += val * n`.  However, it can be used if you pass the total number of correct predictions of each batch into `AverageMeter` for ACC calculation, and pass loss sum of whole batch into `AverageMeter` for loss calculation. You can use the standard version of `AverageMeter` copied from other codebase, but need to check what is passed into this function.

**Comment by AgentDS** [comment]
We will update this function. Thank you!
