### ISSUE TITLE
The number of clients should be given to the server sampler?

### ISSUE THREAD

**Issue by ElegantLin** [SMILELab-FL/FedLab#306]
Dear authors, thanks for your great work. I am reading the code of this framework. I found that for the synchronized server sampler, the number of clients should be passed to the Sampler so as to sample the clients in the training process. [Here](https://github.com/SMILELab-FL/FedLab/blob/release-v1.3.0/fedlab/contrib/algorithm/basic_server.py#L24) is the link to the specific code. Do you agree with me, or do you have a better idea of this?

Thanks!

**Comment by ElegantLin** [comment]
I think you want to pass a sampler to the server so as to sample the client more purposely. However, you have not finished the feature development. Thus, I think it is better to pass the num_client to the server at this time.

**Comment by AgentDS** [comment]
We actually have this. Please check the code of NetworkManager. In the network initialization stage, each client network will report the local client number to server network manager. ServerHandler is only in charge of training related process, rather than communication topology.

**Comment by ElegantLin** [comment]
Thanks for your answer. I ran the `standalone.py` example as guided in the `Readme` and met the bug. Do you have a simple example to run the basic synchronize version? Thanks!

**Comment by AgentDS** [comment]
You mean the scaled version?

**Comment by AgentDS** [comment]
Could you please show me the feedback of the code?

**Comment by ElegantLin** [comment]
I am in the `master` branch, and the output is given in the screenshot.

<img width="1001" alt="image" src="https://github.com/SMILELab-FL/FedLab/assets/16239478/6b8028ce-7100-4987-a988-5468505eda32">

Or should I try the `release-v1.3` branch if I want to try the single process version?

**Comment by AgentDS** [comment]
I guess I misunderstood your problem. I thought you were asking scale version. Sorry for this. In standalone, the handler's num_clients was assigned in StandalonePipeline (as shown in Line30 below):
<img width="767" alt="Screenshot 2023-06-01 at 11 56 25 PM" src="https://github.com/SMILELab-FL/FedLab/assets/19991349/f3c8eb18-bdba-4a0c-a573-24c45445784d">

Since the standalone only uses one client trainer, the handler's num_clients will be assigned as same as trainer's num_clients

**Comment by AgentDS** [comment]
> I am in the `master` branch, and the output is given in the screenshot.
> 
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/16239478/242776912-6b8028ce-7100-4987-a988-5468505eda32.png">
> Or should I try the `release-v1.3` branch if I want to try the single process version?
> 
> Thanks!

My local code has no problem on this demofor release-v1.3, could you please try release-v1.3? The error you showed, it seems the sampler tries to sample from 0 clients. We have not tested the latest sampler yet.

**Comment by ElegantLin** [comment]
Sure. I tried `release-v1.3` and it worked. BTW, I found there is a function called `save_dict`. May I know where the location is?

Thanks!

**Comment by AgentDS** [comment]
This function is deprecated in the previous version. 
```python
def save_dict(dict, path):
    with open(path, 'wb') as f:
        pickle.dump(dict, f)


def load_dict(path):
    with open(path, 'rb') as f:
        return pickle.load(f)
```

We can use `torch.save` and `torch.load` to replace these two functions.

**Comment by ElegantLin** [comment]
Thanks for your patient response!
