### ISSUE TITLE
run unit_test.py error:  list index out of range

### ISSUE THREAD

**Issue by shuaocilang** [SMILELab-FL/FedLab#312]
when I  run unit_test.py, I found an error in basic_server.py: 'list index out of range'. 
in basic_server.py line 118.
![屏幕截图 2023-06-12 125035](https://github.com/SMILELab-FL/FedLab/assets/63042369/f7840324-c00e-496d-bb6d-a3e652273e55)
![屏幕截图 2023-06-12 125055](https://github.com/SMILELab-FL/FedLab/assets/63042369/0062f53f-044c-4ba2-b815-cb9a9b8b3678)

**Comment by Zengdun-cs** [comment]
This bug has been fixed.
