### ISSUE TITLE
No cross-process scenario tutorial.

### ISSUE THREAD

**Issue by hacker-jerry** [SMILELab-FL/FedLab#316]
In Readme, you mentioned that you can accelerate through multithreading, but there is no corresponding code example. The ipynb given is only the standlone version of the code. I would like to ask if you use the framework to achieve multi-client multi-threaded synchronous operation?

**Comment by Zengdun-cs** [comment]
The jupyter notebook seems cannot run a multi-process program. So we provide no tutorials in notebook format for that. 
However, we provide an example project for cross-process simulation. Please see [this](https://github.com/SMILELab-FL/FedLab/tree/master/examples/cross-process-mnist). The standard pipeline implementation in a notebook is provided in [this](https://github.com/SMILELab-FL/FedLab/blob/master/tutorials/pipeline_tutorial.ipynb).
