### ISSUE TITLE
About FedOpt (using bias-corrected momentum or not)

### ISSUE THREAD

**Issue by bird-two** [SMILELab-FL/FedLab#317]
Thans for your excellent code.

Lines 50-63 in [FedOpt](https://github.com/SMILELab-FL/FedLab/blob/master/fedlab/contrib/algorithm/fedopt.py)
```
self.momentum = self.beta1 * self.momentum + (1 - self.beta1) * delta
delta_2 = torch.pow(delta, 2)
if self.option == "adagrad":
    self.vt += delta_2
elif self.option == "yogi":
    self.vt = self.vt - (
            1 - self.beta2) * delta_2 * torch.sign(self.vt - delta_2)
else:
    # adam
    self.vt = self.beta2 * self.vt + (1 - self.beta2) * delta_2
serialized_parameters = self.model_parameters + self.lr * self.momentum / (
            torch.sqrt(self.vt) + self.tau)
```
I note that in the original paper of adam [1] and also the pytorch website of adam optimizer, the bias-corrected first (and second) moment estimate is used for updating, i.e., ($beta_1$ to the power of $t$, from [1])
$$\hat{m}_t = m_t /(1-\beta_1^t)$$

$$\hat{v}_t = v_t /(1-\beta_2^t)$$

$$\theta_t = \theta_{t-1} - \alpha \cdot \hat{m}_t / (\sqrt{\hat{v}_t} + \epsilon)$$

Also, in [1], it has been shown that using bias-corrected momentum is better. Since I can not find the original code of "Adaptive Federated Optimization" (which is written in tensorflow, yet I still can not find the main code in their provided github code), so I am not sure which one I should use.

Thanks for your time and help. 

[1] Adam A method for stochastic optimization

**Comment by Zengdun-cs** [comment]
I implement this part strictly follows the Algorithm 2 in the original paper "Adaptive Federated Optimization" regardless of priori works. This algorithms work quite well in my experiments, especially FedYogi.

**Comment by bird-two** [comment]
Thanks, I have checked the original [code](https://github.com/google-research/federated/blob/master/optimization/trainer.py) of "Adaptive Federated Optimization", which used the default optimizer of `tf.keras.optimizers.Adam` as their server optimizer. So I think they use the bias-corrected momentum in their experements for both [adam](https://github.com/keras-team/keras/blob/v2.12.0/keras/optimizers/adam.py#L26-L216) and  [yogi](https://github.com/google-research/federated/blob/master/utils/optimizers/yogi.py).

Thanks for your kind reply. If the issue actually deserves some value, I think we can add some comments in the code to remind the users of this issue.

**Comment by Zengdun-cs** [comment]
Yes, sure.
