### ISSUE TITLE
某些算法的参数描述没有给出

### ISSUE THREAD

**Issue by hua-zi** [SMILELab-FL/FedLab#318]
**Describe the bug**

某些算法的参数描述没有给出（如ifca,Power-of-choice）
下面为 `IFCAServerHander.setup_optim()`
```
 def setup_optim(self, share_size, k, init_parameters):
        """_summary_
        Args:
            share_size (_type_): _description_
            k (_type_): _description_
            init_parameters (_type_): _description_
        """
        assert k == len(init_parameters)
        self.k = k
        self.share_size = share_size
        self.global_models = init_parameters
        self.shared_paramters = Aggregators.fedavg_aggregate(self.global_models)[0:self.share_size]
```
请问能不能在unit_test.py文件中加上其他算法的例子呀 🥺

**Comment by Zengdun-cs** [comment]
抱歉造成一些不方便，我个人还忙于其他科研任务，所以fedlab的更新比较慢，目前主要在日常维护。
unit_test主要测试了核心模块，目前没有添加对算法的测试。
如果在用的时候有什么问题，可以随时提issue，工作时间内看到我一般都会很快回。
此外，如果你在本地使用过程用对fedlab觉得不好的地方，欢迎修改后提交pull request。

**Comment by hua-zi** [comment]
我看到readme中说框架实现了per-Fedavg，请问这部分代码在哪里呀

**Comment by Zengdun-cs** [comment]
@hua-zi  之前有个用户贡献过代码，版本更新没来得及整理，你可以看他的库。https://github.com/KarhouTam/Per-FedAvg
