### ISSUE TITLE
About FedDyn (the implementation of updates of $h_t$ may be wrong)

### ISSUE THREAD

**Issue by bird-two** [SMILELab-FL/FedLab#319]
Thanks for your great work of this code.

Lines 21-25 in [FedDyn](https://github.com/SMILELab-FL/FedLab/blob/master/fedlab/contrib/algorithm/feddyn.py)
```
def global_update(self, buffer):
    parameters_list = [ele[0] for ele in buffer]
    self.h = self.h - self.alpha * (1.0/self.num_clients) * (sum(parameters_list) - self.model_parameters)
    new_parameters = Aggregators.fedavg_aggregate(parameters_list) - 1.0 / self.alpha * self.h
    self.set_model(new_parameters)
```
Based on the originial paper "Federated learning based on dynamic regularization", the update rule is 
$$h^t = h^{t-1} - \alpha \frac{1}{m} \left(\sum_{k\in P_t} \theta_k^t -\theta^{t-1}\right)$$
This equation may be confusing (yet not rare, see the proof of scaffold), and it can be written more clearly as
$$h^t = h^{t-1} - \alpha \frac{1}{m} \left(\sum_{k\in P_t} (\theta_k^t -\theta^{t-1})\right)$$
It can be validated by the paragraph of _key property of Algorithm 1_ on Page 5, that $h^t\rightarrow 0$ when $\theta^t$ converge. We think we can check the original code to validate this issue. Now I have not checked the original code.

**Comment by AgentDS** [comment]
Please check [this version](https://github.com/SMILELab-FL/FedLab-benchmarks/blob/9b7575a769712014865b1f99962cabce03642245/fedlab_benchmarks/feddyn/server.py#L60C52-L60C52) and [this](https://github.com/SMILELab-FL/FedLab-benchmarks/blob/9b7575a769712014865b1f99962cabce03642245/fedlab_benchmarks/feddyn/server.py#L77).  The global model should be `avg_mdl_param + avg_local_grad`.

**Comment by AgentDS** [comment]
We will check the version in the link you mentioned. Thank you very much.

**Comment by ElegantLin** [comment]
I also think `FedDyn` is incorrect because I tried several parameters in `FedDyn`, and all the losses will go infinite finally.  I did not check the code and algorithm but I notice that `FedDyn` is not tested.

**Comment by AgentDS** [comment]
The version I mentioned in the comment has been tested and there is a [performance report](https://github.com/SMILELab-FL/FedLab-benchmarks/tree/master/fedlab_benchmarks/feddyn). You can verify the code version of FedDyn.

**Comment by ElegantLin** [comment]
Thanks. I will check it out.

**Comment by Zengdun-cs** [comment]
Thank you for this feedback. I have fixed this part, and we will test it later.
