### ISSUE TITLE
Compression tutorial only samples one client despite regardless of sampling_ratio and total_client

### ISSUE THREAD

**Issue by techwizrd** [SMILELab-FL/FedLab#320]
**Describe the bug**
The communication tutorial notebook defines the total number of clients `args.total_client = 100` and the proportion of clients participating in each round `args.sampling_ratio = 0.1`. We expect `100 * 0.1 = 10` clients to be sampled every round for training. However, only one client is sampled each round for training.

**Environment**
The bug appeared on:
1. Python 3.10.6
2. PyTorch 2.0.1+cu117
3. FedLab d6b13e20614498a419abe20dd46638ab718b3a15
4. `tutorials/communication_tutorial.ipynb`
5. The number of clients sampled is always 1.

**Additional context**

This is because the `fedlab.contrib.algorithm.basic_server.SyncServerHandler`, the base class fo r `CompressServerHandeler`, sets `self.num_clients = 0` instead of accepting `num_clients` as a parameter to `SyncServerHandler.__init__()`. The code then chooses the number of clients participating in a given round `self.round_participants = max(1, int(self.sample_ratio * self.num_clients))` which always resolved to 1.

**Comment by Zengdun-cs** [comment]
Thanks for your kind feedback.  `self.num_clients` surely is initialized by accepting a parameter. Somehow, it was modified in our previous update. 
I have fixed this problem. Please check the latest version of the master branch.

**Comment by techwizrd** [comment]
Thanks! I was fixing it an opening a pull request at the same time (#321). I fixed a couple other small bugs in the communication tutorial as well.
