### ISSUE TITLE
Error while running "Heirarchial Federated Learning " from examples

### ISSUE THREAD

**Issue by vinaBira** [SMILELab-FL/FedLab#332]
**Describe the bug**
All three bash files from https://github.com/SMILELab-FL/FedLab/blob/master/examples/hierarchical-hybrid-mnist/ are getting stale  at line "network 0 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3003, rank 0, world size: 3, backend gloo, ethernet None." before that erroras " UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")" 

**Environment**
Environment you use when bug appears:
1. Python 3.8.16
2. Pytorch Version: 1.13.1
3. FedLab version : Version: 1.3.0
4. https://github.com/SMILELab-FL/FedLab/blob/master/examples/hierarchical-hybrid-mnist/ 

Kindly let me now if any more information required from my end.

**Comment by Zengdun-cs** [comment]
Please make sure that you start scripts with the command ``bash launch_eg.sh``. 
If this doesn't work out, please show me the information shown in the terminal. :)

**Comment by vinaBira** [comment]
I ran the command and failed with error:
Traceback (most recent call last):
  File "/home/cloudlabgpu1/FedLab/examples/hierarchical-hybrid-mnist/serial_client.py", line 51, in <module>
    manager_.run()
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/fedlab/core/network_manager.py", line 38, in run
    self.main_loop()
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/fedlab/core/client/manager.py", line 88, in main_loop
    self._trainer.local_process(payload=payload, id_list=id_list)
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/fedlab/contrib/algorithm/basic_client.py", line 137, in local_process
    data_loader = self.dataset.get_dataloader(id, self.batch_size)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/fedlab/contrib/dataset/pathological_mnist.py", line 94, in get_dataloader
    dataset = self.get_dataset(id, type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/fedlab/contrib/dataset/pathological_mnist.py", line 83, in get_dataset
    dataset = torch.load(os.path.join(self.path, type, "data{}.pkl".format(id)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cloudlabgpu1/venv/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../datasets/mnist/train/data2.pkl'

@Zengdun-cs 
I just had one more doubt if we are running bash cript with Ip address 127.0.0.0, then how are we configuring the diiferent machines to connect ? Can you give me some reference to understand the logic for connection to setup and work.
Thanking in advance!!

**Comment by vinaBira** [comment]
I tried with only with two groups instead of 3 :
ran the command for "bash launch_topserver_eg.sh &
bash launch_cgroup1_eg.sh & wait"

code run became stale while running : 
17:02:40 - network 2 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 2, world size: 3, backend gloo, ethernet None.
17:02:40 - network 0 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3003, rank 0, world size: 3, backend gloo, ethernet None.
17:02:40 - network 0 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3002, rank 0, world size: 3, backend gloo, ethernet None.
17:02:41 - network 2 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3003, rank 2, world size: 3, backend gloo, ethernet None.
17:02:48 - network 1 - INFO - torch.distributed connection is initializing with ip address 127.0.0.1:3003, rank 1, world size: 3, backend gloo, ethernet None.
17:02:48 - torch.distributed.distributed_c10d - INFO - Added key: store_based_barrier_key:1 to store for rank: 0
17:02:48 - torch.distributed.distributed_c10d - INFO - Added key: store_based_barrier_key:1 to store for rank: 1
17:02:48 - torch.distributed.distributed_c10d - INFO - Added key: store_based_barrier_key:1 to store for rank: 2
17:02:48 - torch.distributed.distributed_c10d - INFO - Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
17:02:48 - torch.distributed.distributed_c10d - INFO - Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
17:02:48 - torch.distributed.distributed_c10d - INFO - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 3 nodes.
17:02:48 - network 1 - INFO - Sent package to destination 0, message code MessageCode.SetUp, content length 1
17:02:48 - network 0 - INFO - Received package from source 1, message code MessageCode.SetUp, content length 1
17:02:48 - network 2 - INFO - Sent package to destination 0, message code MessageCode.SetUp, content length 1
17:02:48 - network 0 - INFO - Received package from source 2, message code MessageCode.SetUp, content length 1

not updating or working for long time, can we refer something more to understand the code framework better?

**Comment by Zengdun-cs** [comment]
I'm sorry for not getting back to you sooner. Our code updates a few times while the hierarchical example did not. It brings some bugs.  I will fix this example as soon as possible (maybe this weekend.) Before that, if you are interested in our distributed communication in FL, you can try [cross-process](https://github.com/SMILELab-FL/FedLab/tree/master/examples/cross-process-mnist) scenarios first.

For your concern, I have for you here a simple [tutorial](https://fedlab.readthedocs.io/en/master/tutorials/distributed_communication.html) for customizing communication. 

For the last issue, it is because the worker is not launched, so the server always waits for the local update information. Communication protocols are implemented as a loop, please see our [illustration](https://fedlab.readthedocs.io/en/master/tutorials/communication_strategy.html). 

I hope my response could help you. Please feel free to reach out to me.

**Comment by vinaBira** [comment]
@Zengdun-cs Thank you so much for reply and material for reference.

**Comment by vinaBira** [comment]
@Zengdun-cs Could you please inform me once update to example is done? Thanking in advance.

**Comment by Zengdun-cs** [comment]
I have fixed the issue. Somehow, I cannot push the branch due to git network problems. 

Maybe you can fix it by replacing the code segment in serial_client.py and single_client.py:
```
dataset = PathologicalMNIST(root='../../datasets/mnist/',
                            path="../../datasets/mnist/",
                            num_clients=10,
                            preprocess=True)
```
The issue is because that the dataset is not preprocessed. 

Moreover,  I also notice some bugs(typos) and you can fix them locally:
1. basic_client -> basic_server in line 5 top_server.py;
2. num -> num_clients in serial_client.py and single_client.py.

**Comment by vinaBira** [comment]
@Zengdun-cs Thank you so much for Solution.
Example is working now.
