### ISSUE TITLE
PartitionedMNIST 数据划分没有 balance 选项

### ISSUE THREAD

**Issue by hua-zi** [SMILELab-FL/FedLab#335]
```python
class PartitionedCIFAR10(FedDataset):
    def __init__(self,
                 root,
                 path,
                 dataname,
                 num_clients,
                 download=True,
                 preprocess=False,
                 balance=True,
                 partition="iid",
                 unbalance_sgm=0,
                 num_shards=None,
                 dir_alpha=None,
                 verbose=True,
                 seed=None,
                 transform=None,
                 target_transform=None) -> None:
```
```python
class PartitionedMNIST(FedDataset):
    def __init__(self,
                 root,
                 path,
                 num_clients,
                 download=True,
                 preprocess=False,
                 partition="iid",
                 dir_alpha=None,
                 verbose=True,
                 seed=None,
                 transform=None,
                 target_transform=None) -> None:
```
PartitionedMNIST 数据划分没有 balance 选项，和PartitionedCIFAR10不太一样
PartitionedCIFAR10的划分方式有``"iid"``, ``shards``, ``"dirichlet"``
而PartitionedMNIST的划分方式为``"noniid-#label"``, ``"noniid-labeldir"``, ``"unbalance"`` and ``"iid"``
为什么不统一呀，如果未来统一的话，会按照哪种形式呀
再请问PartitionedCIFAR10没有``"noniid-#label"``划分方式，是需要自己去按照PartitionedMNIST一样用VisionPartitioner实现吗🙏
PartitionedMNIST没有``dirichlet``划分，是需要自己实现还是直接使用``"noniid-labeldir"``呀

**Comment by AgentDS** [comment]
你可以自己加这个参数，只需要调用我们之前写的partioner接口就可以。迪利克雷一般是说partition="noniid-labeldir"。不统一的原因是，我们提供的PartitionedCIFAR10的划分方案是FedDyn的，其他的PartitionedMNIST是根据[NIID-bench](https://arxiv.org/pdf/2102.02079.pdf)划分的。比较推荐NIID-bench的这个版本。PartitionedMNIST里面的划分方案其实也可以划分cifar10的，只是需要替换数据下载/加载的部分。你可以参考[这里的几个数据集写法](https://github.com/SMILELab-FL/FedNoisy/tree/main/fednoisy/data/NLLData/FedNLL)。还加了预加载的选项
