### ISSUE TITLE
libc++abi: terminating due to uncaught exception of type gloo::EnforceNotMet:  op.nread == op.preamble.nbytes. 

### ISSUE THREAD

**Issue by takumiSudo** [SMILELab-FL/FedLab#340]
**Background**
hi, I am new to the FedLab scheme, so this can be some easy fix that I am not aware of! I was attracted to the async federated learning that is already implemented in your examples section. 

**Problem**
Now when I run some of the preset simulations in the fedlab/examples, such as hierarchical-hybrid-mnist it seems to give me this error below : 

Recreation: 
```
cd /path/to/Fedlab/examples/ hierarchical-hybrid-mnist
bash launch_eg.sh
```

```python
17:39:25 - network 1 - INFO - Sent package to destination 0, message code MessageCode.SetUp, content length 1
libc++abi: terminating due to uncaught exception of type gloo::EnforceNotMet: [enforce fail at /Users/runner/work/pytorch/pytorch/pytorch/third_party/gloo/gloo/transport/uv/pair.cc:248] op.nread == op.preamble.nbytes. 
```

**Environment**
Environment you use when bug appears:
1. Python version: 3.11
2. PyTorch Version : 2.1.0
3. FedLab version: most recent

**Additional context**
There was a similar issue in this [[https://github.com/pytorch/pytorch/issues/2530]] thread but I was not able to solve it.

Any help would be helpful! Thanks!!

**Comment by AgentDS** [comment]
Please try PyTorch 1.8

**Comment by takumiSudo** [comment]
Thank you for the support.
I tried with Pytorch 1.8.0(not supported by pypi anymore). This however, had some issues running into the fedlab code itself.

```python
    dist.init_process_group(
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
```

I assume this is because the pytorch version before 1.9 did not support the torch functions?
Any help would be helpful! Thanks!!

**Comment by AgentDS** [comment]
Please use `torch.distributed.is_available()` to check whether your machine supports `torch.distributed`. If it returns `False`, then your machine does not support it, and you can only use the standalone mode. I guess you are using MacOS?

If it is Linux system, the command below works for me to install torch 1.8.0 in conda environment:
`conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c nvidia -y`

**Comment by takumiSudo** [comment]
The `torch.distributed.is_available()` seems to be working fine. I am running of macos, M1 Chip which might be causing the problem.

**Comment by AgentDS** [comment]
Actually, we do not support MacOS currently. PyTorch distributed has some differences between MacOS system and Linux system in communication part. Hope we can make FedLab available on MacOS for future versions.

**Comment by takumiSudo** [comment]
Understood. Thanks for the support!
