### ISSUE TITLE
tutorial for training sent140

### ISSUE THREAD

**Issue by Young1403** [SMILELab-FL/FedLab#341]
Hello, is there a tutorial for training sent140? Change the minist example to sent140, how to change the dataset interface?
Hope to get your reply！
Thank you～

**Comment by Zengdun-cs** [comment]
We provide docs of using Leaf [here](https://github.com/SMILELab-FL/FedLab/tree/master/datasets).

**Comment by Young1403** [comment]
@Zengdun-cs I replaced the MNIST data interface with Sent140 in the 'examples/standalone-mnist/standalone.py' script, and when I run it, I get the following traceback:

Traceback (most recent call last):
  File "standalone.py", line 76, in <module>
    pipeline.main()
  File "../../fedlab/core/standalone.py", line 40, in main
    self.trainer.local_process(broadcast, sampled_clients)
  File "../../fedlab/contrib/algorithm/basic_client.py", line 139, in local_process
    data_loader = self.dataset.get_dataloader(id, self.batch_size)
AttributeError: 'Sent140Dataset' object has no attribute 'get_dataloader'.

How should I handle this? Can you provide a complete example of running Sent140 training? Thank you very much.

**Comment by Young1403** [comment]
I have solved it.
thanks
