### ISSUE TITLE
Seaborn dependency not specified

### ISSUE THREAD

**Issue by techwizrd** [SMILELab-FL/FedLab#347]
**Describe the bug**
`from fedlab.contrib.algorithm.basic_client import SGDSerialClientTrainer` fails with `ModuleNotFoundError: no module named 'seaborn'`.

This is because `fedlab.utils.dataset.functional` imports `seaborn` and `matplotlib` for use in the `feddate_scatterplot()` function, but the dependency is not specified in `install_requires` in `setup.py`.

**Environment**
Environment you use when bug appears:
1. Python version: Python 3.11.4
3. PyTorch Version: PyTorch 2.1.2+cpu
4. FedLab version: fedlab [49cf058](https://github.com/SMILELab-FL/FedLab/commit/49cf058e6ac35e56f6379ac5b601cef3ad2452f0)

**Additional context**
Since `seaborn` and `matplotlib` are only used for those two functions, the import should be move into those functions and `seaborn` should be marked as an optional dependency.

**Comment by techwizrd** [comment]
It looks like this bug was introduced in f6960bb9eecc9156d19faa502faf84fe6ce8bd85.

**Comment by AgentDS** [comment]
yeah, you are right. I just fix it by adding `seaborn` in `setup.py` and `requirements.txt`
