### ISSUE TITLE
TypeError: The `dash_mantine_components.Text` component (version 0.14.2)

### ISSUE THREAD

**Issue by hadoop54** [SMILELab-FL/FedLab#350]
**Describe the bug**
TypeError: The `dash_mantine_components.Text` component (version 0.14.2) with the ID "exp_progress_txt" received an unexpected keyword argument: `color`

**Environment**
Environment you use when bug appears:
5. the detailed error

**Additional context**
  File "****/fedlab/board/front/layout.py", line 19, in <module>
    label=dmc.Center(dmc.Text("-%", color="indigo", id="exp_progress_txt", size=18)),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by hadoop54** [comment]
test_demo.py



***@***.***
 
From: Dun Zeng
Date: 2024-04-24 22:31
To: SMILELab-FL/FedLab
CC: hadoop54; Author
Subject: Re: [SMILELab-FL/FedLab] TypeError: The `dash_mantine_components.Text` component (version 0.14.2) (Issue #350)
请问是跑哪部分代码报的错？

**Comment by dunzeng** [comment]
test_demo.py不是给用户用的脚本，如果需要quick start请看我们的文档或者readme

**Comment by hadoop78** [comment]
python.exe E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py --total_client 100 --com_round 10 --sample_ratio 0.1 --batch_size 128 --epochs 3 --lr 0.1 --port 8040 

Traceback (most recent call last):
  File "E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py", line 11, in <module>
    from fedlab.board import fedboard
  File "E:\Remote\Slave1\FedLab\fedlab\board\fedboard.py", line 14, in <module>
    from fedlab.board.front.app import viewModel, create_app, _set_up_layout, _add_chart, _add_section, _add_callbacks
  File "E:\Remote\Slave1\FedLab\fedlab\board\front\app.py", line 11, in <module>
    from fedlab.board.front.layout import card_state, cyto_graph, card_overall_performance, page_performance, selection, \
  File "E:\Remote\Slave1\FedLab\fedlab\board\front\layout.py", line 115, in <module>
    [dmc.Col(dmc.TextInput(
     ^^^^^^^
AttributeError: module 'dash_mantine_components' has no attribute 'Col'

**Comment by dunzeng** [comment]
> python.exe E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py --total_client 100 --com_round 10 --sample_ratio 0.1 --batch_size 128 --epochs 3 --lr 0.1 --port 8040
> 
> Traceback (most recent call last): File "E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py", line 11, in from fedlab.board import fedboard File "E:\Remote\Slave1\FedLab\fedlab\board\fedboard.py", line 14, in from fedlab.board.front.app import viewModel, create_app, _set_up_layout, _add_chart, _add_section, _add_callbacks File "E:\Remote\Slave1\FedLab\fedlab\board\front\app.py", line 11, in from fedlab.board.front.layout import card_state, cyto_graph, card_overall_performance, page_performance, selection, File "E:\Remote\Slave1\FedLab\fedlab\board\front\layout.py", line 115, in [dmc.Col(dmc.TextInput( ^^^^^^^ AttributeError: module 'dash_mantine_components' has no attribute 'Col'

请问有安装[requirements.txt](https://github.com/SMILELab-FL/FedLab/blob/master/fedlab/board/requirements.txt)的依赖吗？

**Comment by hadoop78** [comment]
完整安装了，发现目前这个版本没有Col了，不过去官网查找了一下，发现出现了GridCol，我就改成这个可以运行了


不过发现里面还有dmc这个库变动比较多，还有好几个问题








 ----------Reply to Message----------
 On Sun, Jun 9, 2024 22:51 PM Dun ***@***.***&gt; wrote:

  

  
python.exe E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py --total_client 100 --com_round 10 --sample_ratio 0.1 --batch_size 128 --epochs 3 --lr 0.1 --port 8040
 
Traceback (most recent call last): File "E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py", line 11, in from fedlab.board import fedboard File "E:\Remote\Slave1\FedLab\fedlab\board\fedboard.py", line 14, in from fedlab.board.front.app import viewModel, create_app, _set_up_layout, _add_chart, _add_section, _add_callbacks File "E:\Remote\Slave1\FedLab\fedlab\board\front\app.py", line 11, in from fedlab.board.front.layout import card_state, cyto_graph, card_overall_performance, page_performance, selection, File "E:\Remote\Slave1\FedLab\fedlab\board\front\layout.py", line 115, in [dmc.Col(dmc.TextInput( ^^^^^^^ AttributeError: module 'dash_mantine_components' has no attribute 'Col'
  
请问有安装requirements.txt的依赖吗？

**Comment by dunzeng** [comment]
> 完整安装了，发现目前这个版本没有Col了，不过去官网查找了一下，发现出现了GridCol，我就改成这个可以运行了 不过发现里面还有dmc这个库变动比较多，还有好几个问题
> […](#)
> ----------Reply to Message---------- On Sun, Jun 9, 2024 22:51 PM Dun ***@***.***&gt; wrote: python.exe E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py --total_client 100 --com_round 10 --sample_ratio 0.1 --batch_size 128 --epochs 3 --lr 0.1 --port 8040 Traceback (most recent call last): File "E:\Remote\Slave1\FedLab\examples\standalone-mnist-board\standalone.py", line 11, in from fedlab.board import fedboard File "E:\Remote\Slave1\FedLab\fedlab\board\fedboard.py", line 14, in from fedlab.board.front.app import viewModel, create_app, _set_up_layout, _add_chart, _add_section, _add_callbacks File "E:\Remote\Slave1\FedLab\fedlab\board\front\app.py", line 11, in from fedlab.board.front.layout import card_state, cyto_graph, card_overall_performance, page_performance, selection, File "E:\Remote\Slave1\FedLab\fedlab\board\front\layout.py", line 115, in [dmc.Col(dmc.TextInput( ^^^^^^^ AttributeError: module 'dash_mantine_components' has no attribute 'Col' 请问有安装requirements.txt的依赖吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，感谢反馈，我们查一下之前的依赖库版本。

**Comment by dunzeng** [comment]
依赖版本问题已修复，请查看[requirements.txt](https://github.com/SMILELab-FL/FedLab/blob/master/fedlab/board/requirements.txt)
