### ISSUE TITLE
No module named 'fedlab.core.client.scale'

### ISSUE THREAD

**Issue by xierui78** [SMILELab-FL/FedLab#351]
**Describe the bug**
ModuleNotFoundError: No module named 'fedlab.core.client.scale'

**Environment**
Environment you use when bug appears:

3. FedLab 1.2.0
4. github中stoCFL源代码，提示使用Fedlab1.2.0
5. the detailed error
  File "/opt/runfl/StoCFL/trainer.py", line 5, in <module>
    from fedlab.core.client.scale.trainer import SerialTrainer
ModuleNotFoundError: No module named 'fedlab.core.client.scale'

**Additional context**

**Comment by dunzeng** [comment]
这里是版本错误，Fedlab版本应该为1.2.1。

我已重新整理开源代码，请参考StoCFL[原repo](https://github.com/dunzeng/StoCFL)。

**Comment by dunzeng** [comment]
如果后续仍有问题，欢迎通过issues提问。
